version: '3'
services:
  web: 
    image: dockerdemoweb
    restart: always
    expose:
    - '80'
    depends_on:
      - app
  app: 
    image: dockerdemoapp
    restart: always
    depends_on:
      - db
  db:
    container_name: dockerdemosql
    image: dockerdemodb
    ports:
    - '48945:1433'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "4000:4000"